name: PlanetFxServerSystems
version: 2.4.2
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.ServerSystem.SSMaster.SSMaster

commands:
  cs:
    description: PlanetFxServerSystem Commands
    usage: /cs