name: PlanetFxServerSystems
version: 1.2.1
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.ServerSystem.SSMaster.SSMaster

commands:
  cs:
    description: PlanetFxServerSystem Commands
    usage: /cs