name: PlanetFxServerSystems
version: 1.1.3
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.ServerSystem.SSMaster.SSMaster

commands:
  ss:
    description: PlanetFxServerSystem Commands
    usage: /ss